name: API Automation Tests

on:
  push:
    branches:
      - main

jobs:
  api-tests:
    runs-on: ubuntu-latest

    env:
      DATABASE_URL: mysql+pymysql://root:root123!@127.0.0.1:3306/products

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root123!
          MYSQL_DATABASE: products
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h 127.0.0.1 -proot123!"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=10

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.14"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create Logs and Reports Folders
        run: |
          mkdir -p logs
          mkdir -p reports

      - name: Check MySQL Database
        run: |
          sudo apt-get update
          sudo apt-get install -y mysql-client

          echo "===== SHOW DATABASES ====="
          mysql -h 127.0.0.1 -uroot -proot123! -e "SHOW DATABASES;"

          echo "===== SHOW TABLES ====="
          mysql -h 127.0.0.1 -uroot -proot123! products -e "SHOW TABLES;"

      - name: Start FastAPI Server
        run: |
          uvicorn main:app --host 127.0.0.1 --port 8000 --log-level debug > logs/uvicorn.log 2>&1 &
          sleep 15

      - name: Run API Tests
        run: |
          python -m pytest --html=reports/report.html --self-contained-html

      - name: Show Uvicorn Log
        if: always()
        run: |
          echo "========== UVICORN LOG =========="
          cat logs/uvicorn.log

      - name: Upload HTML Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: API-Test-Report
          path: reports/report.html

      - name: Upload Uvicorn Log
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Uvicorn-Log
          path: logs/uvicorn.log